version: '3.1'

services:
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-example}
      TZ: ${TZ:-Asia/Tokyo}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${MYSQL_PORT_HOST:-3306}:3306
    volumes:
      - type: volume
        source: golang_project_mysql
        target: /var/lib/mysql
        volume:
          nocopy: true

networks:
  default:
    name: golang_project_network
volumes:
  golang_project_mysql:
